<img src="Smart_Fresh.jpg" alt="Smart and Fresh Logo" style="float: left; margin-right: 10px;" />

<div style="display: flex; justify-content: center;">
    <div style="margin-right: 20px;">
        <table>
            <tr>
                <td colspan="4" align="center"><strong>Sandwich Prices</strong></td>
            </tr>
            <tr>
                <td align="center"><strong>Menu #</strong></td>
                <td align="center"><strong>Sandwich</strong></td>
                <td align="center"><strong>6"</strong></td>
                <td align="center"><strong>12"</strong></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Cold Cut</td>
                <td>\$3.75</td>
                <td>\$5.50</td>
            </tr>
            <tr>
                <td>2</td>
                <td>BLT</td>
                <td>\$3.75</td>
                <td>\$5.50</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Italian</td>
                <td>\$4.25</td>
                <td>\$6.75</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Meatball</td>
                <td>\$3.75</td>
                <td>\$5.50</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Chicken</td>
                <td>\$4.75</td>
                <td>\$7.75</td>
            </tr>
            <tr>
                <td>6</td>
                <td>Steak</td>
                <td>\$4.75</td>
                <td>\$7.75</td>
            </tr>
            <tr>
                <td>7</td>
                <td>Pastrami</td>
                <td>\$4.75</td>
                <td>\$6.75</td>
            </tr>
        </table>
    </div>
    <div>
        <table>
            <tr>
                <td colspan="4" align="center"><strong>Sandwich Cost</strong></td>
            </tr>
            <tr>
                <td align="center"><strong>Menu #</strong></td>
                <td align="center"><strong>Sandwich</strong></td>
                <td align="center"><strong>6"</strong></td>
                <td align="center"><strong>12"</strong></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Cold Cut</td>
                <td>\$0.70</td>
                <td>\$1.33</td>
            </tr>
            <tr>
                <td>2</td>
                <td>BLT</td>
                <td>\$0.73</td>
                <td>\$1.39</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Italian</td>
                <td>\$0.81</td>
                <td>\$1.54</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Meatball</td>
                <td>\$0.65</td>
                <td>\$1.23</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Chicken</td>
                <td>\$0.93</td>
                <td>\$1.78</td>
            </tr>
            <tr>
                <td>6</td>
                <td>Steak</td>
                <td>\$1.05</td>
                <td>\$2.02</td>
            </tr>
            <tr>
                <td>7</td>
                <td>Pastrami</td>
                <td>\$0.80</td>
                <td>\$1.52</td>
            </tr>
        </table>
    </div>
    <div style="margin-left: 20px;">
    <table>
      <tr>
        <td colspan="3" align="center"><strong>Shifts</strong></td>
      </tr>
      <tr>
        <td><strong>Morning</strong></td>
        <td>1000</td>
        <td>1059</td>  
      </tr>
      <tr>
        <td><strong>Lunch</strong></td>
        <td>1100</td>
        <td>1359</td>  
      </tr>
      <tr>
        <td><strong>Mid-Day</strong></td>
        <td>1400</td>
        <td>1559</td>  
      </tr>
      <tr>
        <td><strong>Dinner</strong></td>
        <td>1600</td>
        <td>2059</td>  
      </tr>
      <tr>
        <td><strong>Evening</strong></td>
        <td>2100</td>
        <td>2200</td>  
      </tr>        
    </table>
  </div>
</div>


<div style="display: flex; justify-content: center;">
    <div style="margin-right: 20px;">
        <table>
            <tr>
                <td colspan="2" align="center"><strong>Promotions</strong></td>
            </tr>
            <tr>
                <td><strong>January</strong></td>
                <td>\$5 Footlong</td>
            </tr>
            <tr>
                <td><strong>February</strong></td>
                <td>25% off Steak Sandwich</td>
            </tr>
            <tr>
                <td><strong>October</strong></td>
                <td>25% off Italian Sandwich</td>
            </tr>
            <tr>
                <td><strong>November</strong></td>
                <td>\$5 Footlong</td>
            </tr>
        </table>
    </div>
    <div>
        <table>
            <tr>
                <td colspan="2" align="center"><strong>Business Priorities (KPIs)</strong></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Quality</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Customer Satisfaction</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Cost</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Gross Sales</td>
            </tr>
        </table>
    </div>
</div>


<div class="alert alert-block alert-info"><b>Info:</b> You are a store manager for a leading international sandwich franchise.  You have been asked to conduct analysis for your store to identify some of the issues it has been having over the past year.</div>

# Import required Libraries

In [1]:
import numpy as np
import csv

# Read in .csv file as NumPy Array

In [4]:
store = np.array(list(csv.reader(open('Store 7141 Raw Data.csv'))))
store

array([['', '', '', ..., '', '', ''],
       ['Trans_id', 'Menu_id', 'Sand_id', ..., '', '', ''],
       ['7141.42739.4326', '1', '2', ..., '50847', '', ''],
       ...,
       ['7141.43100.8882', '4', '1', ..., '', '', ''],
       ['7141.43100.8889', '2', '2', ..., '', '', ''],
       ['7141.43100.8958', '5', '1', ..., '', '', '']], dtype='<U15')

# Cleaning NumPy Arrays

In [6]:
store_edit = store[1:]
store_edit

array([['Trans_id', 'Menu_id', 'Sand_id', ..., '', '', ''],
       ['7141.42739.4326', '1', '2', ..., '50847', '', ''],
       ['7141.42739.4535', '6', '2', ..., '69076', '', ''],
       ...,
       ['7141.43100.8882', '4', '1', ..., '', '', ''],
       ['7141.43100.8889', '2', '2', ..., '', '', ''],
       ['7141.43100.8958', '5', '1', ..., '', '', '']], dtype='<U15')

In [7]:
store_cleaned = np.delete(store_edit, np.s_[-11:], axis=1) #try -3 first to show that it's not enough
store_cleaned

array([['Trans_id', 'Menu_id', 'Sand_id', ..., 'Value', 'Quality',
        'Grade'],
       ['7141.42739.4326', '1', '2', ..., '25', '32', '81'],
       ['7141.42739.4535', '6', '2', ..., '28', '18', '73'],
       ...,
       ['7141.43100.8882', '4', '1', ..., '23', '28', '77'],
       ['7141.43100.8889', '2', '2', ..., '11', '28', '65'],
       ['7141.43100.8958', '5', '1', ..., '22', '32', '79']], dtype='<U15')

In [8]:
store_cleaned.shape #Note: if you want # of data points, you want to exclude the first row

(50848, 24)

In [ ]:
#same thing as np.delete above
store_edit[:, 0:-11:]

# Slicing NumPy Arrays

In [48]:
Survey_Headers = ['Conv', 'Wait', 'Value', 'Quality','Grade']
Survey_Headers

['Conv', 'Wait', 'Value', 'Quality', 'Grade']

In [49]:
header_row = store_cleaned[0]
header_row

array(['Trans_id', 'Menu_id', 'Sand_id', 'Employees', 'Bread_CT',
       'Cheese_CT', 'Protein_CT', 'Produce_CT', 'Wrap_CT', 'Payment_CT',
       'Cycle', 'Labor_Cost', 'Bread_Cost', 'Cheese_Cost', 'Protein_Cost',
       'Produce_Cost', 'Wrap_Cost', 'Total_Cost', 'Price', 'Conv', 'Wait',
       'Value', 'Quality', 'Grade'], dtype='<U15')

In [50]:
# for i in Survey_Headers:
#     print(np.where(store_cleaned == i))

# "ctrl + /" to comment out code    
for i in Survey_Headers:
    print(np.where(store_cleaned == i)[0], np.where(store_cleaned == i)[1])

[0] [19]
[0] [20]
[0] [21]
[0] [22]
[0] [23]


In [51]:
Survey_Results = store_cleaned[1:, range(19,24)]
Survey_Results

array([['6', '18', '25', '32', '81'],
       ['9', '18', '28', '18', '73'],
       ['8', '12', '11', '32', '63'],
       ...,
       ['4', '22', '23', '28', '77'],
       ['6', '20', '11', '28', '65'],
       ['8', '17', '22', '32', '79']], dtype='<U15')

In [ ]:
#alternative methodology
store_cleaned[1:, 19:24:]

# Calculate Summary Statistics

In [52]:
### do incorrect way first ###
# np.mean(Survey_Results[:, 0])

np.mean(Survey_Results[:, 0].astype(float))

6.350463154168388

In [53]:
Survey_Fixed = Survey_Results.astype(float)
Survey_Fixed

array([[ 6., 18., 25., 32., 81.],
       [ 9., 18., 28., 18., 73.],
       [ 8., 12., 11., 32., 63.],
       ...,
       [ 4., 22., 23., 28., 77.],
       [ 6., 20., 11., 28., 65.],
       [ 8., 17., 22., 32., 79.]])

In [54]:
np.mean(Survey_Fixed, axis=0)

array([ 6.35046315, -6.9851712 , 23.46144315, 27.34352076, 50.17025587])

In [55]:
print(np.median(Survey_Fixed, axis=0))
print(np.std(Survey_Fixed, axis=0)) #you can change to sample std dev with "ddof = 1" added in
print(np.max(Survey_Fixed, axis=0))
print(np.min(Survey_Fixed, axis=0))

[ 7. -8. 24. 29. 51.]
[ 1.94836055 15.65848552  8.69478189  9.42650847 19.00310302]
[ 10.  35.  53.  44. 105.]
[  1. -50.   1.   1. -25.]


In [56]:
from scipy.stats import mode

mode(Survey_Fixed, axis=0)[0][0] #have to put a double [0] because it maintains an extra wrapper, 
                                #can also input  "keepdims=True" to remove warning (says in warning)

8.0

# Formatting Outputs

In [31]:
mean = np.mean(Survey_Fixed, axis=0)
median = np.median(Survey_Fixed, axis=0)
modes = mode(Survey_Fixed, axis=0, keepdims=True)[0][0] 
std_dev = np.std(Survey_Fixed, axis=0)
max_values = np.max(Survey_Fixed, axis=0)
min_values = np.min(Survey_Fixed, axis=0)

In [19]:
for i, headers in enumerate(Survey_Headers): #enumerate gives a combination of a (#, item)
    print(f"Statistics for column '{headers}':")
    print(f"  Mean: {mean[i]}")      # f-strings are string literals that have an f before the opening quotation mark.
    print(f"  Median: {median[i]}")  # They format expressions enclosed in curly braces to their resulting values   
    print(f"  Mode: {modes[i]}")
    print(f"  Standard Deviation: {std_dev[i]}")
    print(f"  Max: {max_values[i]}")
    print(f"  Min: {min_values[i]}")
    print()

Statistics for column 'Conv':
  Mean: 6.350463154168388
  Median: 7.0
  Mode: 8.0
  Standard Deviation: 1.9483605538939086
  Max: 10.0
  Min: 1.0

Statistics for column 'Wait':
  Mean: -6.985171199874133
  Median: -8.0
  Mode: -22.0
  Standard Deviation: 15.658485520706819
  Max: 35.0
  Min: -50.0

Statistics for column 'Value':
  Mean: 23.461443152988377
  Median: 24.0
  Mode: 28.0
  Standard Deviation: 8.694781894486175
  Max: 53.0
  Min: 1.0

Statistics for column 'Quality':
  Mean: 27.343520758353492
  Median: 29.0
  Mode: 37.0
  Standard Deviation: 9.426508470736291
  Max: 44.0
  Min: 1.0

Statistics for column 'Grade':
  Mean: 50.17025586563612
  Median: 51.0
  Mode: 50.0
  Standard Deviation: 19.00310301667647
  Max: 105.0
  Min: -25.0



# Python Exercise 3 - Descriptive Statistics

<table>
            <tr>
                <td colspan="2" align="left"><strong>Survey Goals</strong></td>
            </tr>
            <tr>
                <td><strong>Convenience</strong></td>
                <td>6</td>
            </tr>
            <tr>
                <td><strong>Wait</strong></td>
                <td>12</td>
            </tr>
            <tr>
                <td><strong>Value</strong></td>
                <td>18</td>
            </tr>
            <tr>
                <td><strong>Quality</strong></td>
                <td>24</td>
            </tr>
            <tr>
                <td><strong>Overall</strong></td>
                <td>60</td>
            </tr>
        </table>

### 1. Based on our survey goals from Corporate, where do we seem to be failing the most?

We seem to be failing the most with our Wait rating.

### 2. Apply the same summary statistics to all process times. Where do we seem to spend a majority of our sandwich making process?
    a.) Cycle Times: Bread_CT, Cheese_CT, ..., Payment_CT, & Cycle

In [67]:
Process_Headers = ['Bread_CT', 'Cheese_CT', 'Protein_CT', 'Produce_CT', 'Wrap_CT', 'Payment_CT', 'Cycle']

In [68]:
for i in Process_Headers:
    print(np.where(store_cleaned == i)[0], np.where(store_cleaned == i)[1])

[0] [4]
[0] [5]
[0] [6]
[0] [7]
[0] [8]
[0] [9]
[0] [10]


In [69]:
Process_Times = store_cleaned[1:, list(range(4,11))].astype(float)
Process_Times

array([[ 40.,  41.,  18., ...,  21.,  39., 230.],
       [ 45.,  43.,  21., ...,  19.,  51., 231.],
       [ 80.,  32.,  25., ...,  17.,  27., 197.],
       ...,
       [ 55.,  27.,  17., ...,  12.,  29., 179.],
       [ 48.,  38.,  18., ...,  16.,  38., 282.],
       [ 41.,  27.,   6., ...,  18.,  38., 167.]])

In [70]:
def d_stats(Survey_Fixed):
    mean = np.mean(Survey_Fixed, axis=0)
    median = np.median(Survey_Fixed, axis=0)
    modes = mode(Survey_Fixed, axis=0, keepdims=True)[0][0] 
    std_dev = np.std(Survey_Fixed, axis=0)
    max_values = np.max(Survey_Fixed, axis=0)
    min_values = np.min(Survey_Fixed, axis=0)
    return mean, median, modes, std_dev, max_values, min_values

In [71]:
mean, median, modes, std_dev, max_values, min_values = d_stats(Process_Times)

In [72]:
for i, headers in enumerate(Process_Headers): #enumerate gives a combination of a (#, item)
    print(f"Statistics for column '{headers}':")
    print(f"  Mean: {mean[i]}")      # f-strings are string literals that have an f before the opening quotation mark.
    print(f"  Median: {median[i]}")  # They format expressions enclosed in curly braces to their resulting values   
    print(f"  Mode: {modes[i]}")
    print(f"  Standard Deviation: {std_dev[i]}")
    print(f"  Max: {max_values[i]}")
    print(f"  Min: {min_values[i]}")
    print()

Statistics for column 'Bread_CT':
  Mean: 71.92101795582828
  Median: 73.0
  Mode: 81.0
  Standard Deviation: 29.18582522740088
  Max: 228.0
  Min: 5.0

Statistics for column 'Cheese_CT':
  Mean: 32.96660569945129
  Median: 32.0
  Mode: 31.0
  Standard Deviation: 9.935684473544224
  Max: 86.0
  Min: 5.0

Statistics for column 'Protein_CT':
  Mean: 14.074852007001397
  Median: 13.0
  Mode: 10.0
  Standard Deviation: 6.096056076232438
  Max: 41.0
  Min: 1.0

Statistics for column 'Produce_CT':
  Mean: 50.623930615375535
  Median: 50.0
  Mode: 47.0
  Standard Deviation: 16.389245474510822
  Max: 143.0
  Min: -20.0

Statistics for column 'Wrap_CT':
  Mean: 15.90225578696875
  Median: 15.0
  Mode: 14.0
  Standard Deviation: 4.011905824746231
  Max: 34.0
  Min: 6.0

Statistics for column 'Payment_CT':
  Mean: 108.54787893091037
  Median: 118.0
  Mode: 120.0
  Standard Deviation: 49.737489968900206
  Max: 241.0
  Min: -47.0

Statistics for column 'Cycle':
  Mean: 294.03654099553563
  Median: 

In [ ]:
def d_stats(headers):
    array_columns = []
    for i in Headers:
        array_columns.append(np.where(store_cleaned == i)[1][0])
    
    Survey_Results = store_cleaned[1::, range(array_columns[0], array_columns[len(array_columns)-1]+1)]
    
    Survey_Fixed = Survey_Results.astype(float)
    
    means = np.mean(Survey_Fixed, axis=0)
    medians = np.median(Survey_Fixed, axis=0)
    stds = np.std(Survey_Fixed, axis=0)
    maxes = np.max(Survey_Fixed, axis=0)
    mins = np.min(Survey_Fixed, axis=0)
    modes = mode(Survey_Fixed, axis=0)[0]
    
    for i, j in enumerate(Headers):
        print(f"Statistics for column '{j}':")
        print(f"  Mean: {means[i]:.2f}")
        print(f"  Median: {medians[i]:.2f}")
        print(f"  Mode: {modes[i]:.2f}")
        print(f"  Standard Deviation: {stds[i]:.2f}")
        print(f"  Max: {maxes[i]:.2f}")
        print(f"  Min: {mins[i]:.2f}")
        print()